# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2icQUORkzcFeY8olQfiEQbgpOeQPocw
"""

import pandas as pd

df = pd.read_csv('/content/SampleSuperstore.csv')

print(df.head())

print(df.info())

print(df.describe())

print(df.isnull().sum())
print(f"Number of duplicate rows: {df.duplicated().sum()}")

df = df.drop_duplicates()

print(df.describe())

print(df['Category'].value_counts())
print(df['Sub-Category'].value_counts())
print(df['Region'].value_counts())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('SampleSuperstore.csv')

try:
    df['Order Date'] = pd.to_datetime(df['Order Date'])
except Exception as e:
    print(f"Error converting Order Date to datetime: {e}")


if df.isnull().sum().any():
    print("Warning: There are missing values in the dataset.")
    print(df.isnull().sum())


df = df.drop_duplicates()

# Sales and Profit Over Time
try:
    sales_profit_time = df.groupby(df['Order Date'].dt.to_period('M')).sum()[['Sales', 'Profit']]
    sales_profit_time.plot()
    plt.title('Sales and Profit Over Time')
    plt.show()
except Exception as e:
    print(f"Error plotting Sales and Profit Over Time: {e}")

try:
    category_sales_profit = df.groupby('Category').sum()[['Sales', 'Profit']]
    category_sales_profit.plot(kind='bar')
    plt.title('Sales and Profit by Category')
    plt.show()
except Exception as e:
    print(f"Error plotting Sales and Profit by Category: {e}")

try:
    region_sales_profit = df.groupby('Region').sum()[['Sales', 'Profit']]
    region_sales_profit.plot(kind='bar')
    plt.title('Sales and Profit by Region')
    plt.show()
except Exception as e:
    print(f"Error plotting Sales and Profit by Region: {e}")

try:
    sns.scatterplot(data=df, x='Discount', y='Profit', hue='Category')
    plt.title('Impact of Discount on Profit')
    plt.show()
except Exception as e:
    print(f"Error plotting Impact of Discount on Profit: {e}")